export const FORM_FETCH_LOGIN_REQUEST = 'FETCH_USER_LOGIN_REQUEST';
export const FORM_FETCH_LOGIN_SUCCESS = 'FETCH_USER_LOGIN_SUCCESS';
export const FORM_FETCH_LOGIN_FAILURE = 'FETCH_USER_LOGIN_FAILURE'